### ISSUE TITLE
이벤트 소스 추가요청

### ISSUE THREAD

**Issue by theand** [Kitchu0401/lazecrew-batch-service#11]
다른 분이 운영하시는 https://dev-meetup.github.io/ 에서 사용하는 https://dev-meetup.github.io/data/events.json 데이터가 있는데, onoffmix가 아닌 이벤트 정보도 많이 있습니다. 같이 크롤링이 되면 좋을 것 같습니다.

**Comment by pureugong** [comment]
https://github.com/dev-meetup/dev-meetup.github.io/commits/master/data/events.json
@theand It seems like someone keeps updating this file to show all events on the calendar, right?

**Comment by Kitchu0401** [comment]
@theand 
소스 추가 대환영입니다. :smile:
안그래도 [인프런](https://www.inflearn.com/) 이벤트 정보 확인중이었는데 알려주신 쪽도 알아봐야겠네요!

**Comment by Kitchu0401** [comment]
@pureugong seems manually, individually commits sources to share?
https://github.com/dev-meetup/dev-meetup.github.io

Maybe duplicated event information can be occured.
계속 영어로 말하니까 왠지 내가 문법 틀리지 않을까 걱정돼 :sob:

**Comment by Kitchu0401** [comment]
해당 서비스 내 comment 란에 일단 댓글로 문의드렸어요~ :smiley:

**Comment by Kitchu0401** [comment]
I commented for asking availability and service owner replied positively.
Actually requesting (raw.githubusercontent.com)[https://raw.githubusercontent.com/dev-meetup/dev-meetup.github.io/master/data/events.json] seems better than crawling.

Expected issues are:
- This service is maintained by sharing **collected information** from various sources, therefore deduplication process is additionally required. Currently 45 of 94 events are sourced from **onoffmix.com**.
