### ISSUE TITLE
unnecessary data parameter for POST

### ISSUE THREAD

**Issue by pureugong** [Kitchu0401/lazecrew-batch-service#5]
It seems like "/event/subscriber/ POST", which is for adding "new tag", requires all previous tags.
I think it costs too much for adding one new tag.

**Comment by Kitchu0401** [comment]
For now, whenever request POST api the server overrides previous tag set, just for convinience in dev. :sweat:
Needless to say it must be separated to POST / DELETE, requiring one keyword.

**Comment by Kitchu0401** [comment]
Added server-side validation and chopped into PUT / DELETE, minimize parameter in 23d6672f7b67c244da58ccc6a59e2f3023d70a7b! :nerd_face:

PUT / DELETE requests only require one string!

**Comment by Kitchu0401** [comment]
Checked modified features successfully deployed!
