### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by pureugong** [Kitchu0401/lazecrew-batch-service#6]
https://github.com/Kitchu0401/event-notifier/blob/master/batchs/onoffmixEventNotifier.js#L33
I'm not sure which end point url is on configuration file (maybe /event top page?) and how its performance is good enough to parse dome tree.

I think it's better to call API to get latest event information, which has JSON response format with paging. It's not only for the performance of batch, but also helpful to get more accurate target data.

![sample](https://user-images.githubusercontent.com/5233691/27017102-cffb66e4-4f60-11e7-8487-ac298d284990.png)

**Comment by pureugong** [comment]
Please try it with "X-Requested-With" request header :)

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields

**Comment by Kitchu0401** [comment]
Brilliant, love you :nerd_face: Ill check it out and change this!
https://github.com/request/request#custom-http-headers

**Comment by Kitchu0401** [comment]
I kept old crawling function deprecated-marked and separated, in case of api malfunctioning.
Thx **SO** much about this api-point! 😆

**Comment by pureugong** [comment]
@Kitchu0401 
understood, but why don't we hv both logic on it. Call API first and call current logic as fallback.

**Comment by Kitchu0401** [comment]
@pureugong 
Good point, didn't think about that!
Will check it out soon :3

**Comment by pureugong** [comment]
@Kitchu0401 
Plus, is there any reason why batch pulls event data every 12 min?

**Comment by Kitchu0401** [comment]
@pureugong
Nope, it meant just "5 times in an hour"!
Any idea?

**Comment by pureugong** [comment]
@Kitchu0401 Noap, just curious :)
[FYI] It seems like they are using ES (elastic search engine)  for search api that I mentioned above.

**Comment by Kitchu0401** [comment]
@pureugong 
Yeah I saw api returning props `config.esQuery`
Long since I've suffered from ES but seems we can call it with 'custom-query-options' :P
